version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: jezzpol/eatfit:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dockermvn
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network: